# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='upload',
            field=models.FileField(upload_to=b''),
        ),
    ]
