# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reid', '0002_auto_20160510_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='upload',
        ),
        migrations.AddField(
            model_name='person',
            name='image_path',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
