# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reid', '0003_auto_20160511_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='feature',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
