# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reid', '0004_person_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='feature',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
